version: '3.9'

services:
  givpower-bot:
    image: ghcr.io/giveth/givpower-bot:latest
    environment:
      - NODE_ENV=develop
    restart: unless-stopped
    volumes:
      - ./config:/usr/src/app/config
