version: '3.9'

services:
  givpower-bot:
    image: ghcr.io/giveth/givpower-bot:main
    env_file:
      - ./config/.env
    restart: unless-stopped
    volumes:
      - ./config:/usr/src/app/config
    ports:
      - "3000"
