name: deploy latest givpower-bot image

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATEKEY }}
      - name: SSH and Redeploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATEKEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 20m
          script: |
            cd ~/givpower-bots/givpower-bot-optimism-production
            docker compose stop givpower-bot
            docker compose pull givpower-bot
            docker compose up -d givpower-bot
            cd ~/givpower-bots/givpower-bot-xdai-production
            docker compose stop givpower-bot
            docker compose pull givpower-bot
            docker compose up -d givpower-bot
            docker image prune -a --force
